auto: true
markdown: rdiscount
pygments: true
permalink: /blog/:title

comments:
    provider: disqus
    disqus:
        short_name: hiteshp 

analytics:
    provider: google
    google:
        tracking_id: 'UA-38652154-1'
        domain: 'hiteshp.github.io'

